// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Components.RouteAttribute(
    // language=Route,Component
#nullable restore
#line (1,7)-(1,23) "x:\dir\subdir\Test\TestComponent.cshtml"
"/radio-buttons"

#line default
#line hidden
#nullable disable
    )]
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.OpenElement(1, "InputRadioGroup");
            __builder.OpenElement(2, "InputRadio");
            __builder.AddAttribute(3, "Value", 
#nullable restore
#line (5,34)-(5,41) "x:\dir\subdir\Test\TestComponent.cshtml"
"false"

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(4, "\r\n            ");
            __builder.OpenElement(5, "InputRadio");
            __builder.AddAttribute(6, "Value", 
#nullable restore
#line (6,34)-(6,40) "x:\dir\subdir\Test\TestComponent.cshtml"
"true"

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line (10,12)-(12,5) "x:\dir\subdir\Test\TestComponent.cshtml"

        private string value1 = "true";
    

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
