// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Components.RouteAttribute("/radio-buttons")]
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((global::System.Action)(() => {
// language=Route,Component
#nullable restore
#line 1 "x:\dir\subdir\Test\TestComponent.cshtml"
global::System.Object __typeHelper = "/radio-buttons";

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __o = 
#nullable restore
#line 5 "x:\dir\subdir\Test\TestComponent.cshtml"
                                 "false"

#line default
#line hidden
#nullable disable
            ;
            __o = 
#nullable restore
#line 6 "x:\dir\subdir\Test\TestComponent.cshtml"
                                 "true"

#line default
#line hidden
#nullable disable
            ;
        }
        #pragma warning restore 1998
#nullable restore
#line 10 "x:\dir\subdir\Test\TestComponent.cshtml"
           
        private string value1 = "true";
    

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
